name: flownodes
services:
  - name: mongo
    image: mongo
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: mongo
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: mongo
    bindings:
      - port: 27017
        connectionString: "mongodb://mongo:mongo@${host}:${port}"

  - name: redis
    image: redis
    bindings:
      - port: 6379
        connectionString: "${host}:${port}"

  - name: redis-cli
    image: redis
    args: "redis-cli -h redis MONITOR"

  - name: worker
    project: src/Flownodes.Worker/Flownodes.Worker.csproj
    env:
      - DOTNET_ENVIRONMENT=Staging
      - ORLEANS_CLUSTER_ID=dev
      - ORLEANS_SERVICE_ID=flownodes
