name: flownodes-staging
services:

  - name: mongo
    image: mongo
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: mongo
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: mongo
    bindings:
      - port: 27017
        connectionString: "mongodb://mongo:mongo@${host}:${port}"

  - name: redis
    image: redis
    bindings:
      - port: 6379
        connectionString: "${host}:${port}"

  - name: redis-cli
    image: redis
    args: "redis-cli -h redis MONITOR"

  - name: worker-1
    project: src/Flownodes.Worker/Flownodes.Worker.csproj
    bindings:
      - protocol: https
    env:
      - DOTNET_ENVIRONMENT=Staging
      - ORLEANS_CLUSTER_ID=dev
      - ORLEANS_SERVICE_ID=flownodes
      - ORLEANS_GATEWAY_PORT=30000
      - ORLEANS_SILO_PORT=11111
        
  - name: worker-2
    project: src/Flownodes.Worker/Flownodes.Worker.csproj
    bindings:
      - protocol: https
    env:
      - DOTNET_ENVIRONMENT=Staging
      - ORLEANS_CLUSTER_ID=dev
      - ORLEANS_SERVICE_ID=flownodes
      - ORLEANS_GATEWAY_PORT=30001
      - ORLEANS_SILO_PORT=11112