name: flownodes-edge
services:
- name: redis
  image: redis
  bindings:
    - port: 6379
      connectionString: "${host}:${port}"
      
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
      
- name: edge-node
  project: Flownodes.Edge.Node/Flownodes.Edge.Node.csproj
  env:
    - name: SERVICE-ID
      value: "flownodes"
    - name: CLUSTER-ID
      value: "dev"

- name: api-gateway
  project: Flownodes.Edge.ApiGateway/Flownodes.Edge.ApiGateway.csproj
  bindings:
    - port: 8080
      protocol: http
  env:
    - name: SERVICE-ID
      value: "flownodes"
    - name: CLUSTER-ID
      value: "dev"
